chore(workflows,nv): adjust ci and deploy pipes and node version

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Deploy to Firebase Hosting
+name: CI and deploy to Firebase Hosting
 
 on:
   push:
@@ -8,9 +8,55 @@ permissions:
   contents: write
 
 jobs:
+  ci:
+    runs-on: ubuntu-latest
+    name: Lint, type check and tests (full project)
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+            fetch-depth: 0
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+            node-version: "22"
+            cache: "npm"
+
+      - name: Install dependencies
+        run: npm ci --prefer-offline --no-audit --no-fund
+
+      - name: Run TypeScript type check
+        id: typecheck
+        run: npm run type-check
+
+      - name: Run ESLint
+        id: lint
+        run: npm run lint:all
+
+      - name: Run tests
+        id: tests
+        working-directory: src/
+        run: npm run test:coverage
+
+      - name: Check for failures
+        if: always()
+        run: |
+            if [[  "${{ steps.lint.outcome }}" == "failure" || "${{ steps.typecheck.outcome }}" == "failure" ]]; then
+                echo "## ❌ CI falhou" >> $GITHUB_STEP_SUMMARY
+                echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
+                echo "|---|---|" >> $GITHUB_STEP_SUMMARY
+                echo "| Typecheck | ${{ steps.typecheck.outcome == 'failure' && '❌' || '✅' }} |" >> $GITHUB_STEP_SUMMARY
+                echo "| ESLint | ${{ steps.lint.outcome == 'failure' && '❌' || '✅' }} |" >> $GITHUB_STEP_SUMMARY
+                echo "| Tests | ${{ steps.tests.outcome == 'failure' && '❌' || '✅' }} |" >> $GITHUB_STEP_SUMMARY
+                exit 1
+            fi
+
   build-and-deploy-production:
     runs-on: ubuntu-latest
     name: Build and Deploy Production
+    needs: [ci]
     if: github.ref == 'refs/heads/main'
 
     steps:
@@ -54,6 +100,7 @@ jobs:
   build-and-deploy-develop:
     runs-on: ubuntu-latest
     name: Build and Deploy Develop
+    needs: [ci]
     if: github.ref == 'refs/heads/develop'
 
     steps:
